### PR TITLE
Make ContractFactory.new return a promise

### PR DESCRIPTION
**Pull request by adipascu**
This is a fix for #17 

I just noticed that #18 is already in the works, I posted this as a smaller alternative (feel free to close/not merge).

### CODE REVIEW

**Comment by adipascu** [comment]
PS: The unit test that checks for this specific bug has passed (false positive) because it runs against an older version of `ethjs-query`. This PR does not fix the unit test.

**Comment by SilentCicero** [comment]
@adipascu should be fixed as of version 1.9, can you try again?

**Comment by adipascu** [comment]
@SilentCicero Will test in a week (I'm working a different project right now).

**Comment by SilentCicero** [comment]
@adipascu thanks so much, this has been addressed in 2.0. Thank you for the commit though.

**Pull request closed without merging**
