### PR TITLE
Break codebase into separate pieces

### LINKED ISSUE #3: Move `Contract` class into its own file
## Issue Type

- [ ] Bug (https://github.com/ethjs/ethjs-contract/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [x] Feature (https://github.com/ethjs/ethjs-contract/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

In pursuit of #2, I've begun writing a module that imports this one and wraps it with an event-emitter.

Ideally I'd just inherit from the current `Contract` class, but right now that's not possible, because the `Contract` class [is initialized on each contract creation](https://github.com/ethjs/ethjs-contract/blob/master/src/index.js#L32). This is slightly memory inefficient, but more importantly it prevents me from subclassing the class.

I'm opening this issue to ask if that sounds like an appropriate change to make, before I just open a PR proposing the change.

### PR DESCRIPTION
**Pull request by danfinlay**
In particular, breaks the Contract class into its own file.

This has the benefit of being more modular, allowing subclassing for external modules, as well as saving memory that was previously wasted re-initializing the class on each instance creation.

Fixes #3.

### CODE REVIEW

**Comment by SilentCicero** [comment]
Will review, I like this a lot. Does it change the main method signatures in anyway?

**Comment by danfinlay** [comment]
Nope, all external API is identical, no tests changed, all tests passing.

I want this entirely so I can inherit from this to make an event-emitting subclass of your contract abstraction.

**Comment by SilentCicero** [comment]
Keep going on the event subclasses, that sounds great. I want to see a PR for that soon =D

**Comment by danfinlay** [comment]
Oh, do you think it should just be a different export on this repo?  I was making it its own repo that imports the contract file from this one.

**Comment by SilentCicero** [comment]
@flyswatter oh yeah, it's own is fine

**Pull request closed without merging**
